# Generated by Django 5.2.4 on 2025-07-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='ano',
            new_name='data_publicacao',
        ),
    ]
