# Generated by Django 5.2.5 on 2025-08-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_artigo_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
