# Generated by Django 5.2.5 on 2025-08-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_artigo_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigo',
            name='publicacao',
        ),
        migrations.AddField(
            model_name='artigo',
            name='publicacoes',
            field=models.ManyToManyField(related_name='publicacoes', to='app.publicacao'),
        ),
    ]
