# Generated by Django 5.2.5 on 2025-08-15 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_artigo_publicacao_artigo_publicacoes'),
    ]

    operations = [
    ]
