# Generated by Django 5.2.5 on 2025-08-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20250815_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='publicacoes',
            field=models.ManyToManyField(related_name='artigos', to='app.publicacao'),
        ),
    ]
